In [1]:
import numpy as np

In [2]:
v= np.array([4,7,9])
v

array([4, 7, 9])

In [3]:
v.shape

(3,)

In [4]:
u = np.array([7,4,9])

In [5]:
def igualdad(vector_uno, vector_dos):
    if np.allclose(vector_uno, vector_dos):
        print('los vectores son iguales')
    else:
        print('los vectores no son iguales')


In [6]:
igualdad(v,u)

los vectores no son iguales


In [7]:
#suma de vectores
w = v+u
w

array([11, 11, 18])

In [8]:
#producto por un escalar k
k = 3
u_prima = k*u
u_prima

array([21, 12, 27])

In [9]:
#algunas propiedades 
a = w + (u+v)
b = (w+u) + v
print(a)
print('*'*5)
print(b)
igualdad(a,b)

[22 22 36]
*****
[22 22 36]
los vectores son iguales


In [10]:
a = u + 0
print(a)
print('*'*5)
print(u)
igualdad(a,u)

[7 4 9]
*****
[7 4 9]
los vectores son iguales


In [11]:
a = k *(u + v)
b = k*u + k*v
print(a)
print('*'*5)
print(b)
igualdad(a,b)

[33 33 54]
*****
[33 33 54]
los vectores son iguales


In [12]:
u

array([7, 4, 9])

In [13]:
v

array([4, 7, 9])

In [14]:
#producto punto o producto interno
resultados = []
for i in range(len(u)):

    pro=u[i] * v[i]
    resultados.append(pro)

print(np.array(resultados).sum())
    


137


In [15]:
#o con la función nativa dot de numpy
np.dot(u,v)

137

In [16]:
#son vectores ortogonales
z = np.array([1,2,5])
r = np.array([4,3,-2])
np.dot(z,r)

0

In [17]:
#Distancia euclidiana
from math import dist
dist(u,v)

4.242640687119286

In [18]:
np.linalg.norm(u-v)

4.242640687119285

In [19]:
u

array([7, 4, 9])

In [20]:
v

array([4, 7, 9])

In [21]:
resultados_dos = []
for i in range(len(u)):
    pro=(u[i] - v[i])**2
    resultados_dos.append(pro)
print(np.sqrt(np.array(resultados_dos).sum()))

4.242640687119285


In [22]:
#norma o longitud de un vector
long = []
for i in range(len(u)):
    pro=(u[i])**2
    long.append(pro)
print(np.sqrt(np.array(long).sum()))

12.083045973594572


In [23]:
#con función nativa de numpy
np.linalg.norm(u)

12.083045973594572

In [24]:
#vector unitario 
t = np.array([3/5,4/5])
np.linalg.norm(t)

1.0

In [25]:
#vectores i,j,k

i = np.array([1,0,0])
j = np.array([0,1,0])
k = np.array([0,0,1])


In [26]:
u 

array([7, 4, 9])

In [27]:
print(u*i)
print('*'*5)
print(u*j)
print('*'*5)
print(u*k)



[7 0 0]
*****
[0 4 0]
*****
[0 0 9]


In [28]:
u = u*i + u*j + u*k
u

array([7, 4, 9])

In [37]:
#el ángulo entre dos vectores
a = np.array([3,4]) 
b = np.array([1,2])


In [38]:
#producto punto
pp_a_b = np.dot(a,b) 
pp_a_b

11

In [39]:
#el producto de sus normas o distancias
norm_a = np.linalg.norm(a) 
norm_b = np.linalg.norm(b)
print(norm_a)
print(norm_b)
producto_norms = norm_a*norm_b
print(producto_norms)

5.0
2.23606797749979
11.180339887498949


In [41]:
ang_a_b = pp_a_b/producto_norms
ang_a_b

0.9838699100999074

In [43]:
# Calcular el arco coseno
angulo = np.arccos(ang_a_b)
print(angulo)
# Convertir el ángulo de radianes a grados si es necesario
angulo_en_grados = np.degrees(angulo)
angulo_en_grados

0.17985349979247847


10.304846468766044

In [51]:
## semana dos 

In [46]:
A = np.matrix([a,b])
A

matrix([[3, 4],
        [1, 2]])

In [52]:
# a partir de vectores podemos crear una matriz 

In [50]:
# es posible ver su dimensión mxn
#en este caso m = n , por lo que la matriz es cuadrada
A.shape

(2, 2)

In [53]:
# multiplicación de una matriz por un escalar

B = A*2
B

matrix([[6, 8],
        [2, 4]])

In [54]:
# Suma de matrices

A_B = A + B
A_B

matrix([[ 9, 12],
        [ 3,  6]])

In [56]:
#producto de matrices

A_por_B = A*B
A_por_B

matrix([[26, 40],
        [10, 16]])

In [57]:
B_por_A = B*A
B_por_A

matrix([[26, 40],
        [10, 16]])

In [ ]:
# el producto entre matrices solo es posible si el número de columnas de la matriz A es el mismo que el
# número de renglones de la matriz B.

C = np.matrix([])