In [1]:
import numpy as np

In [2]:
v= np.array([4,7,9])
v

array([4, 7, 9])

In [3]:
v.shape

(3,)

In [4]:
u = np.array([7,4,9])

In [5]:
def igualdad(vector_uno, vector_dos):
    if np.allclose(vector_uno, vector_dos):
        print('los vectores son iguales')
    else:
        print('los vectores no son iguales')


In [6]:
igualdad(v,u)

los vectores no son iguales


In [7]:
#suma de vectores
w = v+u
w

array([11, 11, 18])

In [8]:
#producto por un escalar k
k = 3
u_prima = k*u
u_prima

array([21, 12, 27])

In [9]:
#algunas propiedades 
a = w + (u+v)
b = (w+u) + v
print(a)
print('*'*5)
print(b)
igualdad(a,b)

[22 22 36]
*****
[22 22 36]
los vectores son iguales


In [10]:
a = u + 0
print(a)
print('*'*5)
print(u)
igualdad(a,u)

[7 4 9]
*****
[7 4 9]
los vectores son iguales


In [11]:
a = k *(u + v)
b = k*u + k*v
print(a)
print('*'*5)
print(b)
igualdad(a,b)

[33 33 54]
*****
[33 33 54]
los vectores son iguales


In [12]:
u

array([7, 4, 9])

In [13]:
v

array([4, 7, 9])

In [14]:
resultados = []
for i in range(len(u)):

    pro=u[i] * v[i]
    resultados.append(pro)

print(np.array(resultados).sum())
    


137


In [15]:
#o con la función nativa dot de numpy
np.dot(u,v)

137

In [16]:
#son vectores ortogonales
z = np.array([1,2,5])
r = np.array([4,3,-2])
np.dot(z,r)

0

In [17]:
#Distancia euclidiana
from math import dist
dist(u,v)

4.242640687119286

In [18]:
np.linalg.norm(u-v)

4.242640687119285

In [19]:
u

array([7, 4, 9])

In [20]:
v

array([4, 7, 9])

In [21]:
resultados_dos = []
for i in range(len(u)):
    pro=(u[i] - v[i])**2
    resultados_dos.append(pro)
print(np.sqrt(np.array(resultados_dos).sum()))

4.242640687119285


In [22]:
#norma o longitud de un vector
long = []
for i in range(len(u)):
    pro=(u[i])**2
    long.append(pro)
print(np.sqrt(np.array(long).sum()))

12.083045973594572


In [23]:
#con función nativa de numpy
np.linalg.norm(u)

12.083045973594572

In [24]:
#vector unitario 
t = np.array([3/5,4/5])
np.linalg.norm(t)

1.0